### PR TITLE
New Player and Room Transition

### PR DESCRIPTION
**Pull request by 5H4D0WILA**
here is the new player script/scene and the finished room transition
i know, i was only supposed to change one thing at the time, but i worked on it while working on the player script, so i implemented it aswell

### CODE REVIEW

**Comment by acedogblast** [comment]
Sorry but your going have to rebase to latest master. We have added a lot of work to the master and your pull undoes it.

**Comment by acedogblast** [comment]
You will also need to use the autobuilder what that master uses the new tilesets.

**Comment by 5H4D0WILA** [comment]
That is with the files on your github
And with the autobuilder copying the files

**Comment by 5H4D0WILA** [comment]
You mean the changes in herhome with the new dialogue system?

**Comment by 5H4D0WILA** [comment]
Okay, so
Global.gd:
I changed the position of the player by 16 because my new player wasnt on the grid

HeroHome.gd:
changed the interaction and added the room transition

HeroHome.tscn:
added two collisionshapes because of my interaction code

Indoor(1).tres:
added missing collisions

Dialogue Box.tscn:
changed the pause_mode to "process" because of my disable_input method
that way the dialogue box works and gets input but the player doesnt get input

DialogueBoxNew.tscn:
i just changed it to "process" because of the same reasons as above
dont know what github thinks i also changed

the other three are my added scenes

**Pull request merged**
