### PR TITLE
ui_accept during dialogue to quickly finish printing line

### PR DESCRIPTION
**Pull request by lboklin**
Enables spamming ui_accept key to fast forward dialogue.

### CODE REVIEW

**Comment by Ev1lbl0w** [comment]
This will break text events *(wait pauses, sound effects, auto-skips, etc...)* the way it's implemented.

It's probably way easier to just change the `TypeDelay` to go like 10 times faster, and when the dialogue finishes, reset it's value to the original one.

**Comment by lboklin** [comment]
I did that at first, but I couldn't get it as instant as doing it this way, but I'll change it!

**Comment by acedogblast** [comment]
I just tested the latest changes and found that when rapidly pressing ui_accept keys it can cause mismatch of dialogue with what is presented on screen.

**Comment by lboklin** [comment]
I had that occur at some point during my hacking but I can't reproduce it on this commit. In any case it sounds like that bug resides elsewhere in how the dialogue events are handled.

**Comment by Ev1lbl0w** [comment]
The timer can be really finicky when set to very low values.

I think the best solution for this is to have a different kind of loop: when the user wants to "skip" the text, it should show all of it and process pending events. Try doing something like this:

- Until process queue isn't empty, `pop` the top one.
- The dialogue event stores the position in the text where it happens, so just set `visible_characters = event.pos`
- Process event
- Repeat

**Comment by acedogblast** [comment]
If there is no update to this pull then I will close in a week.

**Pull request closed without merging**
